---
name: Detect

on:
  push:
    branches-ignore:
      - renovate/*

permissions: {}

defaults:
  run:
    # Add `-o pipefail` option to bash
    # References
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  # tag::style[]
  # `tag::<TAG_NAME>[]` and `end::<TAG_NAME>[]` used to write document.
  # `<TAG_NAME>` used to tag attribute of include directive in AsciiDoc.
  # https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions
  style:
    name: Style
    runs-on: ubuntu-22.04
    permissions: {}
    timeout-minutes: 5
    steps:
      - name: Runtime security for GitHub
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          # Because to run `lefthook run lint-fix`.
          disable-file-monitoring: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            raw.githubusercontent.com:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443

      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install task runner
        uses: ./.github/actions/install_tools_with_aqua

      - name: Detect trailing space
        run: |
          lefthook run lint \
            --commands detect-trailing-space

      - name: Detect trailing blank line
        run: |
          lefthook run lint-fix \
            --commands trim-trailing-blank-line

          git diff --exit-code --color=always

      - name: Detect consecutive blank lines
        run: |
          lefthook run lint-fix \
            --commands join-consecutive-blank-lines

          git diff --exit-code --color=always

      - name: Detect file without final newline
        run: |
          lefthook run lint-fix \
            --commands insert-final-newline

          git diff --exit-code --color=always
  # end::style[]
  create_timeline:
    name: Create timeline of this GitHub Actions workflow
    if: ${{ always() }}
    needs:
      - style
    runs-on: ubuntu-22.04
    steps:
      - name: Create timeline of this GitHub Actions workflow
        # yamllint disable-line rule:line-length
        uses: Kesin11/actions-timeline@baa62e018ca5504e2d617502ce1eacf9171e757a # v2.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
