---
name: Test task name

on:
  push:
    paths:
      - .lefthook.yml
      - .lefthook/*.yml
      - .lefthook/task_runner/lefthook/test_task_name/expected.txt
      - .github/workflows/test_task_name.yml
      - .github/actions/install_tools_with_aqua/action.yml

permissions: {}

defaults:
  run:
    # Add `-o pipefail` option to bash
    # References
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    permissions: {}
    timeout-minutes: 5
    steps:
      - name: Create the timeline of GitHub Actions workflow
        # yamllint disable-line rule:line-length
        uses: Kesin11/actions-timeline@fbbb6f71498dbdb3af862970133257532cd48054 # v1.0.0
        with:
          github-token: ${{ github.token }}

      - name: Runtime security for GitHub
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            raw.githubusercontent.com:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443

      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install task runner
        uses: ./.github/actions/install_tools_with_aqua

      - name: Test task name
        run: |
          lefthook run test-dev-env \
            --commands test-task-name
