---
name: Test setup

on:
  push:
    paths:
      - scripts/setup.sh
      - scripts/install_aqua.sh
      - .aqua/aqua.yml
      - .aqua/imports/*.yml
      - .aqua/aqua-checksums.json
      - package.json
      - package-lock.json
      - .ruby-version
      - Gemfile
      - Gemfile.lock
      - .lefthook.yml
      - .lefthook/**/*.yml
      - .github/workflows/test_setup.yml

permissions: {}

defaults:
  run:
    # Add `-o pipefail` option to bash
    # References
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    permissions: {}
    timeout-minutes: 5
    steps:
      - name: Create timeline of this GitHub Actions workflow
        # yamllint disable-line rule:line-length
        uses: Kesin11/actions-timeline@baa62e018ca5504e2d617502ce1eacf9171e757a # v2.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Runtime security for GitHub
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          # Because to run `npm install` on `bash scripts/setup.sh`.
          disable-file-monitoring: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            index.rubygems.org:443
            nodejs.org:443
            objects.githubusercontent.com:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443
            rubygems.org:443

      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Download aqua
        run: bash scripts/deps/download_aqua.sh

      - name: Add aqua to the environment variable `PATH`
        run: |
          # References
          # https://aquaproj.github.io/docs/tutorial/#install-aqua
          echo "$HOME/.local/share/aquaproj-aqua/bin" >> "$GITHUB_PATH"

      - name: Install Node
        # yamllint disable-line rule:line-length
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          check-latest: false
          # Decides a node version from `engines.node` in `package.json`
          # https://github.com/actions/setup-node/blob/b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8/docs/advanced-usage.md#node-version-file
          # v4.0.1 Commit on 2023-12-18
          node-version-file: package.json
          cache: ""

      - name: Install Ruby and Bundler
        # yamllint disable-line rule:line-length
        uses: ruby/setup-ruby@360dc864d5da99d54fcb8e9148c14a84b90d3e88 # v1.165.1
        with:
          # https://github.com/ruby/setup-ruby/blob/5cfe23c062c0aac352e765b1b7cc12ea5255ccc4/action.yml#L8-L9
          # v1.156.0 Commit on 2023-10-12.
          # Decide the version for Ruby from `.ruby-version` file.
          ruby-version: .ruby-version
          # https://github.com/ruby/setup-ruby/blob/5cfe23c062c0aac352e765b1b7cc12ea5255ccc4/action.yml#L17-L21
          # v1.156.0 Commit on 2023-10-12.
          # - Gemfile.lock
          #   the version of the BUNDLED WITH section
          #   from the Gemfile.lock if it exists.
          #   If the file or section does not exist then the same as 'default'.
          # - default
          #   if the Ruby ships with Bundler 2.2+ as a default gem,
          #   that version is used, otherwise the same as 'latest'.
          bundler: Gemfile.lock
          # https://github.com/ruby/setup-ruby/blob/5cfe23c062c0aac352e765b1b7cc12ea5255ccc4/action.yml#L25
          # v1.156.0 Commit on 2023-10-12.
          # Does not install gems with `bundle install`.
          bundler-cache: false

      - name: Run setup
        run: bash scripts/setup.sh
