---
name: Validate Renovate configuration

on:
  push:
    paths:
      - .renovaterc.json
      - .renovate/*.json
      - package-lock.json
      - .lefthook/deps/renovate/validate.yml
      - .aqua/imports/git_hook.yml
      - .github/workflows/validate_renovate_configuration.yml
      - .github/actions/install_tools_with_aqua/action.yml
      - .github/actions/install_node_packages/action.yml

permissions: {}

defaults:
  run:
    # Add `-o pipefail` option to bash
    # References
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-22.04
    permissions: {}
    timeout-minutes: 5
    steps:
      - name: Create timeline of this GitHub Actions workflow
        # yamllint disable-line rule:line-length
        uses: Kesin11/actions-timeline@baa62e018ca5504e2d617502ce1eacf9171e757a # v2.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Runtime security for GitHub
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            nodejs.org:443
            objects.githubusercontent.com:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443

      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install Node packages
        uses: ./.github/actions/install_node_packages

      - name: Validate Renovate configuration with task runner
        uses: ./.github/actions/run_task_runner
        with:
          task_name: deps
          task_runner_args: --commands=validate-renovate-config
